# [START cloudbuild_maven]
steps:
  - name: maven:3.8.6-jdk-11
    entrypoint: mvn
    args: ["clean", "install", "-Dmaven.test.skip=true"]
  - name: maven:3.8.6-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
    
 # APP ENGINE
 # - name: "gcr.io/cloud-builders/gcloud"
 #   args: ["app", "deploy"]

 #CLOUD RUN
 # - name: gcr.io/cloud-builders/gsutil
 #   args:
 #     - '-c'
 #     - |
 #       gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin europe-southwest1-docker.pkg.dev
        
 # SÓLO LA PRIMERA VEZ!!! para crear el repositorio
 # - name: gcr.io/cloud-builders/gcloud
 #   args: ['artifacts', 'repositories', 'create', 'demouserpg', '--repository-format', 'docker', '--location', 'europe-southwest1', '--description', 'Repositorio DemoUser PG']
 
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "europe-southwest1-docker.pkg.dev/$PROJECT_ID/demouserpg/demouserpg:$SHORT_SHA", "--build-arg=JAR_FILE=target/demouserpg*.jar", "."]
    #args: ["build", "-t", "gcr.io/$PROJECT_ID/demouserpg:$SHORT_SHA", "--build-arg=JAR_FILE=target/demouserpg*.jar", "."]
 # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/demouserpg/demouserpg:$SHORT_SHA']
# Deploy container image to Cloud Rungit 
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'demouserpg', '--image', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/demouserpg/demouserpg:$SHORT_SHA', '--region', 'europe-southwest1', '--service-account', 'id-opplus-desarrollo@openmarket-356106.iam.gserviceaccount.com', '--port','8080', '--platform', 'managed', '--allow-unauthenticated']
   
     
images: ["europe-southwest1-docker.pkg.dev/$PROJECT_ID/demouserpg/demouserpg:$SHORT_SHA"]
serviceAccount: 'projects/$PROJECT_ID/serviceAccount/id-opplus-desarrollo@openmarket-356106.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
# [END cloudbuild_maven]